installer:
  image: andreaskoch/dockerized-magento-installer
  container_name: installer
  environment:
    DOMAIN: magento.vm
    MAGENTO_ROOT: /var/www/html/web
    MYSQL_HOST: mysql
    MYSQL_DATABASE: magento
    MYSQL_USER: root
    MYSQL_PASSWORD: a12345
    ADMIN_USERNAME: admin
    ADMIN_FIRSTNAME: John
    ADMIN_LASTNAME: Doe
    ADMIN_PASSWORD: a12345
    ADMIN_FRONTNAME: admin
    ADMIN_EMAIL: admin@example.com
    ENCRYPTIONKEY: 731aea833710535779fe8c7c49bc6c4d
  volumes_from:
    - nginx
  volumes:
    - ./config/installer/php/php.ini:/usr/local/etc/php/php.ini
    - ./config/installer/magerun/n98-magerun.yaml.tmpl:/etc/n98-magerun.yaml.tmpl
    - ./config/installer/magento/local.xml.tmpl:/etc/local.xml.tmpl
    - ./config/installer/magento/fpc.xml.tmpl:/etc/fpc.xml.tmpl
    - ./config/installer/bin/substitute-env-vars.sh:/bin/substitute-env-vars.sh
    - ./config/installer/bin/install.sh:/bin/install.sh
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"
    - "solr:solr"
    - "mysql:mysql"
  entrypoint: /bin/install.sh

nginx:
  image: nginx:latest
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - "php"
  volumes:
    - ./logs/nginx:/var/log/nginx
    - ./config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
    - ./config/ssl/cert.key:/etc/nginx/ssl/cert.key
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf
    - ./config/nginx/includes:/etc/nginx/includes
    - ./config/nginx/custom-locations:/etc/nginx/custom-locations
  volumes_from:
    - php
php:
  image: andreaskoch/dockerized-magento-php
  container_name: php
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"
    - "solr:solr"
    - "mysql:mysql"
  volumes:
    - .:/var/www/html

mysql:
  image: mysql:5.5
  container_name: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: a12345
  command: mysqld --innodb-use-native-aio=0
  volumes:
    - ./data/mysql:/var/lib/mysql

solr:
  image: andreaskoch/dockerized-magento-solr
  container_name: solr

cache:
  image: redis:latest
  container_name: cache

fullpagecache:
  image: redis:latest
  container_name: fullpagecache

sessions:
  image: redis:latest
  container_name: sessions

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  ports:
    - "8080:80"
  links:
    - "mysql:mysql"
  environment:
    PMA_HOST: "mysql"
    PMA_PORT: 3306

